### ISSUE TITLE
RCDスナバのDについて

### ISSUE THREAD

**Issue by TakashiKusachi** [KogakuinRobotProject/bl_motor_d#7]
## RCDスナバのDはショットキーバリア(SBD)よりpn接合型ダイオードの方がいいと思う
RCDスナバのDとしては逆回復特性や降伏電圧の高いpn接合のD（ファストリカバリーダイオード(FRD)と呼ばれている種類）の方がいいはずなのでそれに変えた方がいいと思います。それからスナバ回路にはそんな大電流流れないのでもっと小さいのでも大丈夫では？

そもそもスナバいる？

**Comment by hayate2718** [comment]
このダイオードの逆回復時間が18nsecで降伏電圧が100Vなのですが、具体的にどのくらいの逆回復時間と降伏電圧のものを選んだほうが良いですか？スナバ回路ってそんなに大電流流れないのですね...瞬間電流100Aほど流せるドライバにしたかったので瞬間電流の最大定格をその倍取っていました。スナバ回路はこれつけとけばfet保護は完璧だろうというノリでつけました。

**Comment by TakashiKusachi** [comment]
こいつショットキーバリアダイオード（SBD)じゃなくてDIODES社商標のスーパーバリアダイオードとかいう特殊なやつなのか…
同様にSBDの代替で開発されたものみたいで、高逆回復特性、低vfが特徴みたいだけど、この用途なら低vfは必要ないからもう少し小さくて安いやつでも大丈夫じゃない？というコストのお話になる。それことフリーホイーリングD(FWD)がないのは問題なので、スナバにこんなデカい領域使うなら変えた方がいいと思う。

**Comment by TakashiKusachi** [comment]
https://toshiba.semicon-storage.com/info/docget.jsp?did=13411
これ見てみた？

**Comment by hayate2718** [comment]
一応見たことあります。スナバの設計に使った資料は添付した二つのファイルです。
[sic-mos_snubber_circuit_design_an-j.pdf](https://github.com/hayate2718/bl_motor_d/files/5301074/sic-mos_snubber_circuit_design_an-j.pdf)
[RH984b_05.pdf](https://github.com/hayate2718/bl_motor_d/files/5301075/RH984b_05.pdf)

**Comment by hayate2718** [comment]
現在スナバに使ったダイオードはフリーホイールダイオードに使える性能していますか？一応スナバに関してはどの程度の電流が流れるのかわからなくてかなり多く見積もっていたので、電流がそれほど流れないのであればもともと採用しようとしていた小さいダイオードがあるのでそれを用います。

**Comment by TakashiKusachi** [comment]
富士電機のはIGBTなことを考えるとおそらく数十kW級のアプリケーションな気がする。実際例で一番小さいので30kWとかロボコンの範疇じゃない。主回路浮遊インダクタンスも＞100V級の回路は絶縁距離を保たないといけない特性上大きく出ます。多分このくらいの回路だと数十nH大きくても数十nHくらいでしょう。電流に関しては定常100A取ってるのは現実できじゃないことを考慮しても50A,20kHzで1/4Wの抵抗で大丈夫じゃないかな。
ダイオードの損失設計はわからん。けど、定格電流なんで定常の場合がほとんどだから、瞬間電流が定格超えても問題ない場合がほとんど

FWDにはスーパーバリアダイオードは非常に適していると思います。

**Comment by TakashiKusachi** [comment]
#2 の話に戻るけど、正直アバランシェ破壊はもっとこう電力アプリケーションに入ってからの話な気がしていて、それ以前にFWDがないせいで熱損失破壊してるだけじゃないかと思ってる。
